name: Build (Fabric 1.21.x)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Use the wrapper that’s in your repo (more reliable than forcing a Gradle version)
      - name: Build with Gradle Wrapper
        run: ./gradlew --no-daemon build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: seed-sync-jar
          path: build/libs/*.jar
